auto:
  name: ğŸ¤– Auto
  welcome_message: ğŸ¤– Hi, I'm <b>ChatGPT</b>. What would you like to create?
  parse_mode: html


manual:
  name: ğŸ‘©ğŸ¼â€ğŸ’» Manual
  welcome_message: ğŸ‘©ğŸ¼â€ğŸ’» What would you like to create?
  parse_mode: html
